# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sat Mar  7 21:11:21 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(914, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_4.addWidget(self.graphicsView)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.loadImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadImageButton.setObjectName("loadImageButton")
        self.horizontalLayout_4.addWidget(self.loadImageButton)
        self.revertButton = QtWidgets.QPushButton(self.centralwidget)
        self.revertButton.setObjectName("revertButton")
        self.horizontalLayout_4.addWidget(self.revertButton)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.zoomInButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomInButton.setObjectName("zoomInButton")
        self.horizontalLayout_5.addWidget(self.zoomInButton)
        self.zoomOutButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomOutButton.sizePolicy().hasHeightForWidth())
        self.zoomOutButton.setSizePolicy(sizePolicy)
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.horizontalLayout_5.addWidget(self.zoomOutButton)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.edgeDetect = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edgeDetect.sizePolicy().hasHeightForWidth())
        self.edgeDetect.setSizePolicy(sizePolicy)
        self.edgeDetect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.edgeDetect.setAutoFillBackground(False)
        self.edgeDetect.setObjectName("edgeDetect")
        self.gridLayout = QtWidgets.QGridLayout(self.edgeDetect)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sobelButton = QtWidgets.QRadioButton(self.edgeDetect)
        self.sobelButton.setObjectName("sobelButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.sobelButton)
        self.verticalLayout.addWidget(self.sobelButton)
        self.cannyButton = QtWidgets.QRadioButton(self.edgeDetect)
        self.cannyButton.setChecked(True)
        self.cannyButton.setObjectName("cannyButton")
        self.buttonGroup.addButton(self.cannyButton)
        self.verticalLayout.addWidget(self.cannyButton)
        self.label = QtWidgets.QLabel(self.edgeDetect)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.sigmaSpinBox = QtWidgets.QDoubleSpinBox(self.edgeDetect)
        self.sigmaSpinBox.setMinimum(0.1)
        self.sigmaSpinBox.setMaximum(15.0)
        self.sigmaSpinBox.setSingleStep(0.1)
        self.sigmaSpinBox.setProperty("value", 1.4)
        self.sigmaSpinBox.setObjectName("sigmaSpinBox")
        self.verticalLayout.addWidget(self.sigmaSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.edgeDetectApplyButton = QtWidgets.QPushButton(self.edgeDetect)
        self.edgeDetectApplyButton.setObjectName("edgeDetectApplyButton")
        self.horizontalLayout_6.addWidget(self.edgeDetectApplyButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.edgeDetect, "")
        self.gausDiff = QtWidgets.QWidget()
        self.gausDiff.setObjectName("gausDiff")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gausDiff)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.gausDiff)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.sigma1SpinBox = QtWidgets.QDoubleSpinBox(self.gausDiff)
        self.sigma1SpinBox.setMinimum(0.1)
        self.sigma1SpinBox.setMaximum(75.0)
        self.sigma1SpinBox.setSingleStep(0.1)
        self.sigma1SpinBox.setProperty("value", 1.5)
        self.sigma1SpinBox.setObjectName("sigma1SpinBox")
        self.verticalLayout_2.addWidget(self.sigma1SpinBox)
        self.label_3 = QtWidgets.QLabel(self.gausDiff)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.sigma2SpinBox = QtWidgets.QDoubleSpinBox(self.gausDiff)
        self.sigma2SpinBox.setMinimum(0.1)
        self.sigma2SpinBox.setMaximum(75.0)
        self.sigma2SpinBox.setSingleStep(0.1)
        self.sigma2SpinBox.setProperty("value", 3.0)
        self.sigma2SpinBox.setObjectName("sigma2SpinBox")
        self.verticalLayout_2.addWidget(self.sigma2SpinBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.blobDetectApplyButton = QtWidgets.QPushButton(self.gausDiff)
        self.blobDetectApplyButton.setObjectName("blobDetectApplyButton")
        self.horizontalLayout_7.addWidget(self.blobDetectApplyButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.gausDiff, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 914, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.sobelButton.toggled['bool'].connect(self.sigmaSpinBox.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.loadImageButton)
        MainWindow.setTabOrder(self.loadImageButton, self.revertButton)
        MainWindow.setTabOrder(self.revertButton, self.zoomInButton)
        MainWindow.setTabOrder(self.zoomInButton, self.zoomOutButton)
        MainWindow.setTabOrder(self.zoomOutButton, self.graphicsView)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CVTests"))
        self.loadImageButton.setText(_translate("MainWindow", "Load Image..."))
        self.revertButton.setText(_translate("MainWindow", "Revert"))
        self.zoomInButton.setText(_translate("MainWindow", "+"))
        self.zoomOutButton.setText(_translate("MainWindow", "-"))
        self.sobelButton.setText(_translate("MainWindow", "Pure Sobel"))
        self.cannyButton.setText(_translate("MainWindow", "Canny"))
        self.label.setText(_translate("MainWindow", "Sigma"))
        self.edgeDetectApplyButton.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.edgeDetect), _translate("MainWindow", "Edge Detect"))
        self.label_2.setText(_translate("MainWindow", "Sigma 1"))
        self.label_3.setText(_translate("MainWindow", "Sigma 2"))
        self.blobDetectApplyButton.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gausDiff), _translate("MainWindow", "Diff of Gaus"))

